### ISSUE TITLE
Dimensions of ResNet101 and 3D-ResNext101 features  

### ISSUE THREAD

**Issue by ericwang0701** [hobincar/SGN#1]
Thank you for sharing your amazing work. I'd like to know more details about the ResNet101 and 3D-ResNext101 features that you used in this project. 

In terms of 3D-ResNext101 features, the project link you provided has issues around the output dimensions as pointed out in [here](https://github.com/kenshohara/video-classification-3d-cnn-pytorch/issues/53) and [here](https://github.com/kenshohara/video-classification-3d-cnn-pytorch/issues/21). It would be very helpful if you can share more details on how you generate the 3D-ResNext101 features (e.g. which pre-trained model you used and what's the feature dimensions). I plan to generate 3D-ResNext101 features on my custom videos but I'd like to make sure the format is correct.

Thank you so much for your help and time.

**Comment by hobincar** [comment]
Hi, thank you for visiting my repo.

I modified the original repo a little bit and the changes can be found [here](https://github.com/hobincar/video-classification-3d-cnn-pytorch/commits/master)

For your convenience, I uploaded the pretrained CNN features. Please check.

**Comment by ericwang0701** [comment]
Thank you so much for your reply. Now I'm able to train and evaluate the model for MSVD and MSR-VTT. However, I'm still struggling to generate the caption for a custom video. 

If possible, can you explain the format of the `feats` in the following code? 
`captions = model.describe(feats)`

For a custom video, I computed the ResNet101 and 3DResNext101 features and generated `vid_feats ` where both the shape of `vid_feats["ResNet101"]` and `vid_feats["3DResNext101"]` are `(30, 2048).` (since uniformly sample N = 30) 

But when I call `model.describe(vid_feats )`, I got the following error:

```
/content/SGN/models/visual_encoder.py in forward(self, app_feats, mot_feats)
     19         app_outputs = self.app_linear(app_feats)
     20         mot_outputs = self.mot_linear(mot_feats)
---> 21         return torch.cat([ app_outputs, mot_outputs ], dim=2)
     22 

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```

More details on the format of the `feats`  in `captions = model.describe(feats)` would be very appreciated. Thanks

**Comment by hobincar** [comment]
Can you give me the shape of `app_outputs` and `mot_outputs`? I guess both of them should be `(batch_size, 30, 300)`, where 300 comes from the output dimension of the `app_linear ` and `mot_linear` which map 2048 to 300.

**Comment by ooza** [comment]
@ericwang0701
@hobincar  
Any ideas on how to work with custom videos ?
