### ISSUE TITLE
MSVD_train.csv

### ISSUE THREAD

**Issue by MarcusNerva** [hobincar/SGN#2]
Greetings! Thank you for sharing your work! However, I didn't find any file named 'MSVD_train.csv' to split dataset. Namely, in extract_negative_videos.py, line 130

`
def main(dataset, split):
    if dataset == 'MSVD':
        caption_fpath = "./data/{}/metadata/{}.csv".format(dataset, split)
        vid2captions = load_MSVD_captions(caption_fpath)
    elif dataset == 'MSR-VTT':
        caption_fpath = "./data/{}/metadata/{}.json".format(dataset, split)
        vid2captions = load_MSRVTT_captions(caption_fpath)
    else:
        raise NotImplementedError('Unknown dataset: {}'.format(dataset))

    negative_videos = extract_negative_samples(dataset, vid2captions)
    with open("data/{}/metadata/neg_vids_{}.json".format(dataset, split), 'w') as fout:
        json.dump(negative_videos, fout)
`

There is no such file `caption_fpath = "./data/{}/metadata/{}.csv".format(dataset, split)`

**Comment by hobincar** [comment]
Hi! I added the missing files. Please check and feel free to reopen this issue if there're any other missing files.
